export const securitiesCopy = {
  vi: {
    startTitle: "Hiểu doanh nghiệp trước khi đầu tư.",
    startIntro: "Chọn cổ phiếu để xem dữ liệu và tra cứu tài liệu.",
    tryQuestion: "Gợi ý",
    startExamples: [
      "Điều gì đang thúc đẩy tăng trưởng?",
      "Lợi nhuận có đi cùng dòng tiền?",
      "Rủi ro nào cần theo dõi?",
    ],
    sourceAssuranceTitle: "Đọc nhanh, vẫn kiểm tra được.",
    sourceAssuranceText:
      "Nhận định chính ở ngay trong báo cáo. Mỗi con số và tài liệu gốc đều có chỗ để xem kỹ.",
    openFinancials: "Xem dữ liệu hiện có",
    reportReady: "Báo cáo sẵn sàng",
    reportUnavailable: "Chưa có báo cáo",
    readinessTitle: "Phạm vi kết quả",
    readinessReady: "Báo cáo đã qua các kiểm tra hiện có và có thể tải xuống.",
    growthComparisonUnavailable: "Chưa đủ cơ sở so sánh tăng trưởng",
    readinessShort: {
      ai_answer_unavailable: "Chưa có câu trả lời AI; có thể đọc dữ liệu đã kiểm chứng.",
      ai_validation_failed: "Câu trả lời AI chưa qua kiểm tra; hiện chỉ có dữ liệu.",
      analysis_context_mismatch: "Phân tích chưa khớp phiên bản dữ liệu đang xem.",
      historical_analysis: "Bản phân tích cũ chưa có kiểm tra theo quy trình hiện tại.",
      metrics_omitted: "Một số số liệu thiếu căn cứ đã được loại khỏi báo cáo.",
      claims_omitted: "Một số nhận định thiếu căn cứ đã được loại khỏi báo cáo.",
      research_incomplete: "Chưa đọc đủ nguồn để trả lời toàn bộ câu hỏi.",
      semantic_validation_limited: "Một số diễn giải còn giới hạn kiểm chứng.",
    },
    readinessUnavailable:
      "Chưa có nội dung đủ căn cứ để xuất báo cáo. Dữ liệu và nguồn gốc vẫn có thể xem trong phần chi tiết.",
    viewChecks: "Xem chi tiết kiểm tra",
    viewSources: "Xem căn cứ",
    summary: "Tóm tắt",
    keyFigures: "Các số chính",
    reportSections: {
      performance: "Kết quả kinh doanh",
      earnings_quality: "Chất lượng lợi nhuận",
      cash_and_funding: "Dòng tiền & tài chính",
      outlook: "Triển vọng & điều cần theo dõi",
    },
    questionBeingAnswered: "Câu hỏi của bạn",
    askMoreTitle: "Đào sâu thêm một điểm",
    askMoreText: "Tiếp tục ngay trên dữ liệu và nguồn của báo cáo này.",
    showConversation: "Xem hội thoại",
    reportDetails: "Cách phân tích & giới hạn",
    historicalAnalysis: "Phân tích đã lưu theo định dạng cũ",
    historicalAnalysisNote:
      "Bản này được giữ nguyên để tham khảo. Chạy phân tích mới để có báo cáo theo quy trình kiểm tra hiện tại.",
    retainedNotes: "Ghi chú của bạn",
    roundedValues: "Làm tròn để dễ đọc. Chọn một số để xem giá trị gốc.",
    skip: "Đi tới bàn nghiên cứu",
    portfolio: "Về portfolio",
    language: "Ngôn ngữ",
    newDossier: "Nghiên cứu mới",
    library: "Nghiên cứu đã lưu",
    noDossiers: "Các nghiên cứu đã lưu sẽ xuất hiện ở đây.",
    sharedLibraryNotice: "Lịch sử dùng chung: mọi người có thể xem và xóa nghiên cứu đã lưu.",
    deleteResearch: "Xóa nghiên cứu",
    deleteResearchTitle: "Xóa nghiên cứu đã lưu?",
    deleteResearchDescription:
      "Thao tác này xóa vĩnh viễn mọi phiên bản, xác nhận và cuộc trao đổi tiếp nối của nghiên cứu. Khi dùng lịch sử chung, thay đổi áp dụng với tất cả mọi người và không thể hoàn tác.",
    deleteResearchConfirm: "Xóa vĩnh viễn",
    keepResearch: "Giữ lại",
    researchDeleted: "Đã xóa nghiên cứu đã lưu.",
    sourceLibrary: "Phạm vi nguồn",
    localDesk: "Bàn nghiên cứu local",
    savedLocally: "Lưu tại dịch vụ local",
    sourceBound: "Phân tích gắn với nguồn",
    loading: "Đang mở bàn nghiên cứu",
    retry: "Thử lại",
    close: "Đóng",
    back: "Quay lại",
    eyebrow: "NGHIÊN CỨU DOANH NGHIỆP VIỆT NAM",
    heroLine1: "Từ báo cáo",
    heroLine2: "tới luận điểm.",
    intro:
      "Một không gian để đọc sâu doanh nghiệp, đối chiếu từng con số và hoàn thiện góc nhìn có căn cứ.",
    questionLabel: "Bạn muốn tìm hiểu điều gì?",
    questionPlaceholder: "Ví dụ: Lợi nhuận tăng có đi cùng dòng tiền tốt hơn không?",
    questionHint: "Câu hỏi sẽ dùng doanh nghiệp và kỳ đang chọn.",
    inspectScope: "Xác định phạm vi",
    supported: "Bắt đầu từ nguồn đã có",
    sourceCount: "doanh nghiệp trong danh mục",
    frozen: "Nguồn báo cáo đã lưu",
    frozenNote:
      "Phân tích theo kỳ báo cáo và tài liệu đã lưu; không bao gồm giá thị trường trực tiếp.",
    assuranceTitle: "Luận điểm tốt bắt đầu từ nguồn tốt.",
    assuranceText:
      "Từ giá trị gốc đến phép tính và bản xuất, mỗi bước đều có dấu vết để bạn kiểm tra.",
    steps: [
      {
        title: "Đúng phạm vi",
        text: "Chọn doanh nghiệp, kỳ và nền so sánh có dữ liệu.",
      },
      {
        title: "Rõ căn cứ",
        text: "Mở tài liệu gốc, kiểm tra công thức và xử lý điểm chưa rõ.",
      },
      {
        title: "Tiếp tục làm việc",
        text: "Hỏi sâu hơn, lưu ghi chú và tải báo cáo.",
      },
    ],
    scopeTitle: "Điều chỉnh phạm vi",
    scopeIntro: "Chọn đúng doanh nghiệp và kỳ để bắt đầu phân tích.",
    company: "Doanh nghiệp",
    period: "Kỳ phân tích",
    comparison: "Kỳ so sánh",
    accounting: "Phạm vi kế toán",
    createDossier: "Mở số liệu",
    changeScope: "Đổi kỳ",
    sources: "Nguồn",
    source: "Nguồn",
    documents: "tài liệu",
    noSource: "Chưa có nguồn đáp ứng phạm vi này.",
    fetched: "Lấy nguồn",
    published: "Công bố",
    unknownDate: "Chưa xác định ngày công bố",
    latestNotice: "Kỳ mới nhất trong nguồn đã có",
    chooseCompany: "Chọn doanh nghiệp",
    choosePeriod: "Chọn kỳ",
    working: "Đang xử lý",
    cancel: "Hủy tác vụ",
    cancelled: "Đã hủy tác vụ. Hồ sơ đã lưu vẫn được giữ.",
    researchDossier: "BÁO CÁO DOANH NGHIỆP",
    draft: "Bản nháp",
    approved: "Đã duyệt",
    revision: "Phiên bản",
    saved: "Đã lưu",
    modified: "Chỉnh sửa",
    financials: "Dữ liệu & nguồn",
    analysis: "Báo cáo",
    review: "Ghi chú & kiểm tra",
    history: "Lịch sử",
    ask: "Hỏi tiếp",
    analyze: "Phân tích",
    analyzing: "Đang phân tích",
    modelUnavailable: "Phân tích AI chưa sẵn sàng ở dịch vụ local.",
    approve: "Xác nhận báo cáo",
    export: "Tải báo cáo",
    exportXlsx: "Tải bảng XLSX",
    exportNotes: "Tải báo cáo",
    exportSuccess: "Đã tạo bản xuất cho báo cáo đang xem.",
    overview: "Bức tranh tài chính",
    financialIntro:
      "Giá trị đối chiếu từ nguồn. Chọn một số để mở dấu vết trích xuất và công thức.",
    metric: "Chỉ tiêu",
    absoluteChange: "Chênh lệch",
    relativeChange: "Thay đổi",
    noValue: "Thiếu số liệu",
    calculated: "Tính bằng mã",
    original: "Giá trị gốc",
    corrected: "Người dùng sửa",
    verified: "Đã kiểm chứng",
    needsReview: "Cần kiểm tra",
    openEvidence: "Mở bằng chứng",
    definition: "Định nghĩa",
    formula: "Công thức",
    noFormula: "Chưa tính được với đầu vào hiện có.",
    input: "Đầu vào",
    sourceDetails: "Dấu vết nguồn",
    sourceVersion: "Phiên bản nguồn",
    extraction: "Trích xuất gốc",
    unit: "Đơn vị",
    reportType: "Loại báo cáo",
    parser: "Bộ trích xuất",
    scope: "Phạm vi",
    openOriginal: "Mở tài liệu gốc",
    evidence: "Bằng chứng",
    precision: "Độ chi tiết",
    sourceRights: "Quyền sử dụng",
    notes: "Ghi chú",
    noNotes: "Chưa có ghi chú.",
    editValue: "Sửa số liệu có lý do",
    correctionTitle: "Sửa số liệu",
    correctionIntro:
      "Số gốc và lý do được giữ trong lịch sử. Khi đầu vào đổi, phân tích cần được kiểm tra lại.",
    newValue: "Giá trị mới",
    reason: "Lý do và căn cứ",
    reasonPlaceholder: "Giải thích điều bạn kiểm tra được, tài liệu và vị trí liên quan…",
    saveCorrection: "Lưu thay đổi",
    correctionSaved: "Đã lưu thay đổi và căn cứ.",
    reasonRequired: "Nhập lý do cụ thể để lưu thay đổi.",
    invalidNumber: "Nhập một số hợp lệ, dùng dấu chấm cho phần thập phân.",
    analysisTitle: "Những điều đáng chú ý",
    analysisIntro: "Góc nhìn từ dữ liệu và tài liệu của kỳ báo cáo.",
    noAnalysisTitle: "Chưa có phân tích cho báo cáo này.",
    noAnalysisText: "Xem số liệu đã kiểm chứng hoặc bắt đầu phân tích câu hỏi của bạn.",
    noFakeAI:
      "Các số liệu được tính từ nguồn đã lưu. Chúng chưa thay thế câu trả lời cho câu hỏi nghiên cứu.",
    sourceFact: "Theo nguồn",
    inference: "Suy luận",
    hypothesis: "Cần xác minh",
    reviewAnalysis: "Các kết luận giữ nguyên liên kết tới dữ liệu và nguồn để bạn đọc sâu khi cần.",
    reviewTitle: "Ghi chú và kiểm tra chi tiết",
    reviewIntro: "Thêm góc nhìn của bạn, đối chiếu các điểm chưa rõ hoặc sửa số liệu có căn cứ.",
    noIssues: "Không còn vấn đề mở trong các kiểm tra hiện có.",
    material: "Trọng yếu",
    warning: "Cần lưu ý",
    resolved: "Đã xử lý",
    resolve: "Ghi nhận xử lý",
    resolveHint: "Giải thích cách xử lý. Số liệu chưa xác minh vẫn phải có căn cứ hợp lệ.",
    openIssues: "điểm cần xem",
    blocking: "Các điểm chưa đủ bằng chứng được ghi rõ trong trạng thái báo cáo.",
    approvalTitle: "Xác nhận báo cáo này?",
    approvalIntro:
      "Xác nhận này là tùy chọn và được ghi vào lịch sử. Khả năng xuất báo cáo do kiểm tra tự động của hệ thống quyết định.",
    confirmApproval: "Xác nhận duyệt",
    approvalSuccess: "Đã lưu xác nhận của bạn.",
    approvalCheck: "Tôi đã kiểm tra và xác nhận báo cáo đang xem.",
    approvalBlocked: "Xử lý các vấn đề trọng yếu trước khi duyệt.",
    historyTitle: "Dấu vết công việc",
    historyIntro: "Mở lại báo cáo tại từng lần lưu, cùng dữ liệu và nguồn khi đó.",
    openRevision: "Mở bản lưu",
    currentRevision: "Đang xem",
    context: "Ngữ cảnh đang dùng",
    chatPlaceholder: "Bạn muốn hiểu rõ thêm điều gì?",
    send: "Gửi câu hỏi",
    noChat: "Hỏi tiếp để làm rõ một luận điểm hoặc tìm phần cần kiểm chứng.",
    askExamples: ["Chỉ tiêu nào cần xem kỹ hơn?", "Nền so sánh có điểm gì cần lưu ý?"],
    chatContext: "Câu trả lời dùng dữ liệu và nguồn của báo cáo đang xem.",
    sourceUnavailable: "Nguồn hoặc phép phân tích chưa đủ. Phần đã lưu vẫn được giữ.",
    connectionError:
      "Chưa kết nối được dịch vụ nghiên cứu local. Kiểm tra dịch vụ đang chạy rồi thử lại.",
    generalError: "Thao tác chưa hoàn tất. Dữ liệu đã lưu vẫn được giữ.",
    refreshing: "Đang kiểm tra",
    refreshSources: "Kiểm tra nguồn mới",
    viewAllSources: "Xem danh mục nguồn",
    noCompanies: "Danh mục nguồn chưa sẵn sàng. Thử tải lại khi dịch vụ đã khởi động.",
    select: "Chọn",
    recent: "Gần đây",
    allDossiers: "Báo cáo",
    status: "Trạng thái",
    independent: "Sản phẩm nghiên cứu độc lập của Trần Thiện Nhân",
    supportedScope: "Phạm vi được hỗ trợ",
    publicData: "Nguồn công khai",
    reviewScope: "Xem phạm vi",
    noComparison: "Chưa có kỳ so sánh",
    sessionReady: "Sẵn sàng",
    changedContext: "Đã chuyển ngữ cảnh hồ sơ.",
    copyId: "Mã hồ sơ",
    partial: "Kết quả một phần",
    readyToReview: "Sẵn sàng kiểm tra",
    sourceReference: "Tài liệu tham chiếu",
    more: "Xem chi tiết",
    insideProduct: "Bên trong Nhân",
    searchReports: "Tìm nghiên cứu đã lưu",
    noMatchingReports: "Không có nghiên cứu phù hợp.",
  },
  en: {
    startTitle: "Understand what you invest in.",
    startIntro: "Choose a stock to explore its data and source documents.",
    tryQuestion: "Try asking",
    startExamples: [
      "What is driving growth?",
      "Is profit supported by cash flow?",
      "Which risks should I watch?",
    ],
    sourceAssuranceTitle: "Easy to read. Ready to inspect.",
    sourceAssuranceText:
      "The main findings are in the report. Every figure and original document has a place for closer reading.",
    openFinancials: "View available data",
    reportReady: "Report ready",
    reportUnavailable: "No report yet",
    readinessTitle: "Result coverage",
    readinessReady: "The report passed the available checks and can be downloaded.",
    growthComparisonUnavailable: "Growth comparison is not available",
    readinessShort: {
      ai_answer_unavailable: "There is no AI answer yet; verified data are available.",
      ai_validation_failed: "The AI answer did not pass checks; only data are available.",
      analysis_context_mismatch: "The analysis does not match the data revision being viewed.",
      historical_analysis: "This earlier analysis has no current validation record.",
      metrics_omitted: "Figures without sufficient evidence are excluded.",
      claims_omitted: "Findings without sufficient evidence are excluded.",
      research_incomplete: "Source coverage does not yet address the whole question.",
      semantic_validation_limited: "Some interpretations have limited validation.",
    },
    readinessUnavailable:
      "There is not enough supported content to export a report. The detailed data and original sources remain available.",
    viewChecks: "View detailed checks",
    viewSources: "View evidence",
    summary: "At a glance",
    keyFigures: "Key figures",
    reportSections: {
      performance: "Business performance",
      earnings_quality: "Earnings quality",
      cash_and_funding: "Cash flow & funding",
      outlook: "Outlook & what to watch",
    },
    questionBeingAnswered: "Your question",
    askMoreTitle: "Take a closer look",
    askMoreText: "Continue with this report's exact data and sources.",
    showConversation: "View conversation",
    reportDetails: "Research approach & limitations",
    historicalAnalysis: "Analysis saved in an earlier format",
    historicalAnalysisNote:
      "This version is preserved for reference. Run a new analysis for a report using the current checks.",
    retainedNotes: "Your notes",
    roundedValues: "Rounded for readability. Select a figure to inspect the original value.",
    skip: "Skip to research desk",
    portfolio: "Back to portfolio",
    language: "Language",
    newDossier: "New research",
    library: "Saved research",
    noDossiers: "Your saved research will appear here.",
    sharedLibraryNotice: "Shared history: everyone can view and delete saved research.",
    deleteResearch: "Delete research",
    deleteResearchTitle: "Delete saved research?",
    deleteResearchDescription:
      "This permanently deletes every revision, confirmation, and follow-up conversation in the research. In shared history, the change applies to everyone and cannot be undone.",
    deleteResearchConfirm: "Delete permanently",
    keepResearch: "Keep research",
    researchDeleted: "Saved research deleted.",
    sourceLibrary: "Source coverage",
    localDesk: "Local research desk",
    savedLocally: "Saved in the local service",
    sourceBound: "Research with traceable sources",
    loading: "Opening your research desk",
    retry: "Try again",
    close: "Close",
    back: "Back",
    eyebrow: "VIETNAM COMPANY RESEARCH",
    heroLine1: "From reports",
    heroLine2: "to perspective.",
    intro:
      "A considered space to understand a business, reconcile the numbers and build a view you can substantiate.",
    questionLabel: "What would you like to understand?",
    questionPlaceholder: "For example: Is profit growth supported by stronger cash flow?",
    questionHint: "Your question uses the selected company and reporting period.",
    inspectScope: "Review scope",
    supported: "Start with available sources",
    sourceCount: "companies in the catalog",
    frozen: "Saved reporting sources",
    frozenNote:
      "Analysis uses the reporting period and saved documents; live market prices are not included.",
    assuranceTitle: "A stronger view starts with the source.",
    assuranceText:
      "From the original value to the calculation and export, every step leaves a trail you can inspect.",
    steps: [
      {
        title: "Set the scope",
        text: "Choose a company, period and a supported comparison.",
      },
      {
        title: "Check the evidence",
        text: "Open the original, inspect calculations and resolve questions.",
      },
      {
        title: "Keep working",
        text: "Ask follow-up questions, save notes and download the report.",
      },
    ],
    scopeTitle: "Adjust the research scope",
    scopeIntro: "Choose the company and period to begin the analysis.",
    company: "Company",
    period: "Reporting period",
    comparison: "Comparison period",
    accounting: "Accounting scope",
    createDossier: "Open financial data",
    changeScope: "Change period",
    sources: "Sources",
    source: "Source",
    documents: "documents",
    noSource: "No source currently supports this scope.",
    fetched: "Retrieved",
    published: "Published",
    unknownDate: "Publication date not established",
    latestNotice: "Latest period in available sources",
    chooseCompany: "Choose a company",
    choosePeriod: "Choose a period",
    working: "Working",
    cancel: "Cancel task",
    cancelled: "Task cancelled. Your saved dossier is preserved.",
    researchDossier: "COMPANY REPORT",
    draft: "Draft",
    approved: "Approved",
    revision: "Revision",
    saved: "Saved",
    modified: "Modified",
    financials: "Data & sources",
    analysis: "Report",
    review: "Notes & checks",
    history: "History",
    ask: "Follow up",
    analyze: "Analyze",
    analyzing: "Analyzing",
    modelUnavailable: "AI analysis is not available in the local service yet.",
    approve: "Confirm report",
    export: "Download report",
    exportXlsx: "Download XLSX",
    exportNotes: "Download report",
    exportSuccess: "Export created for the report you are viewing.",
    overview: "The financial picture",
    financialIntro:
      "Values reconciled with their source. Select a number to inspect its extraction trail and calculation.",
    metric: "Metric",
    absoluteChange: "Difference",
    relativeChange: "Change",
    noValue: "Missing data",
    calculated: "Calculated in code",
    original: "Original value",
    corrected: "User correction",
    verified: "Verified",
    needsReview: "Needs review",
    openEvidence: "Open evidence",
    definition: "Definition",
    formula: "Formula",
    noFormula: "Cannot calculate from the available inputs.",
    input: "Inputs",
    sourceDetails: "Source trail",
    sourceVersion: "Source version",
    extraction: "Original extraction",
    unit: "Unit",
    reportType: "Report type",
    parser: "Parser",
    scope: "Scope",
    openOriginal: "Open original document",
    evidence: "Evidence",
    precision: "Precision",
    sourceRights: "Usage rights",
    notes: "Notes",
    noNotes: "No notes yet.",
    editValue: "Correct with a reason",
    correctionTitle: "Correct a value",
    correctionIntro:
      "The original value and your reason remain in history. Analysis needs review when its inputs change.",
    newValue: "New value",
    reason: "Reason and evidence",
    reasonPlaceholder: "Explain what you verified, with the document and location…",
    saveCorrection: "Save changes",
    correctionSaved: "Changes and evidence saved.",
    reasonRequired: "Enter a specific reason for this change.",
    invalidNumber: "Enter a valid number using a decimal point.",
    analysisTitle: "What stands out",
    analysisIntro: "A view grounded in this reporting period's data and documents.",
    noAnalysisTitle: "There is no analysis for this report yet.",
    noAnalysisText: "View verified financial data or start an analysis of your question.",
    noFakeAI:
      "These figures are calculated from saved sources. They do not replace an answer to the research question.",
    sourceFact: "Source fact",
    inference: "Inference",
    hypothesis: "To verify",
    reviewAnalysis:
      "Conclusions keep their links to the data and original sources for deeper reading.",
    reviewTitle: "Notes and detailed checks",
    reviewIntro: "Add your perspective, examine unresolved points or make an evidenced correction.",
    noIssues: "No open issues in the checks currently available.",
    material: "Material",
    warning: "Attention",
    resolved: "Resolved",
    resolve: "Record a resolution",
    resolveHint: "Explain the resolution. Unverified values still require valid evidence.",
    openIssues: "items to review",
    blocking: "Evidence gaps are reflected in the report status.",
    approvalTitle: "Confirm this report?",
    approvalIntro:
      "This optional confirmation is recorded in history. Automatic system checks determine whether the report can be exported.",
    confirmApproval: "Confirm approval",
    approvalSuccess: "Your confirmation has been recorded.",
    approvalCheck: "I have reviewed and confirm the report being viewed.",
    approvalBlocked: "Resolve material issues before approval.",
    historyTitle: "A record of your work",
    historyIntro: "Reopen the report at each save, with its data and sources at that time.",
    openRevision: "Open saved report",
    currentRevision: "Viewing",
    context: "Active context",
    chatPlaceholder: "What would you like to understand further?",
    send: "Send question",
    noChat: "Follow up to clarify a finding or identify what needs verification.",
    askExamples: [
      "Which metrics deserve a closer look?",
      "What should I know about the comparison basis?",
    ],
    chatContext: "Answers use the data and sources of the report being viewed.",
    sourceUnavailable: "A source or analysis is incomplete. Your saved work is preserved.",
    connectionError:
      "The local research service is unreachable. Check that it is running, then try again.",
    generalError: "This action could not be completed. Your saved work is preserved.",
    refreshing: "Checking",
    refreshSources: "Check for new sources",
    viewAllSources: "View source catalog",
    noCompanies: "The source catalog is not ready. Retry once the service has started.",
    select: "Select",
    recent: "Recent",
    allDossiers: "Reports",
    status: "Status",
    independent: "Independent research product by Trần Thiện Nhân",
    supportedScope: "Supported coverage",
    publicData: "Public sources",
    reviewScope: "Review scope",
    noComparison: "No comparison period",
    sessionReady: "Ready",
    changedContext: "Dossier context changed.",
    copyId: "Dossier ID",
    partial: "Partial result",
    readyToReview: "Ready to review",
    sourceReference: "Reference document",
    more: "View details",
    insideProduct: "Inside Nhân",
    searchReports: "Search saved research",
    noMatchingReports: "No matching research.",
  },
};
