export const marketCopy = (locale) =>
  locale === "vi"
    ? {
        title: "Tra cứu thị trường",
        subtitle: "Giá, lịch sử và thông tin doanh nghiệp",
        intro: "Tra cứu nguồn dữ liệu công khai theo mã và sàn đã chọn.",
        dataset: "Dữ liệu",
        quote: "Giá gần nhất",
        history: "Lịch sử giao dịch",
        company: "Thông tin doanh nghiệp",
        refresh: "Cập nhật dữ liệu",
        loading: "Đang đọc nguồn công khai…",
        empty: "Nguồn chưa cung cấp dữ liệu cho lựa chọn này.",
        choose: "Chọn một mã chứng khoán để tra cứu.",
        fetched: "Đọc nguồn lúc",
        sourceDate: "Ngày dữ liệu tại nguồn",
        sourceClock: "Giờ tại nguồn",
        missing: "Chưa có dữ liệu",
        unknownUnit: "Nguồn chưa xác định đơn vị",
        unknownDate: "Nguồn chưa cung cấp ngày hiệu lực",
        stale: "Đang dùng bản đã lưu; dữ liệu có thể đã thay đổi.",
        unsaved: "Dữ liệu chưa lưu được trên máy; lần sau có thể cần tải lại.",
        intraday: "Ảnh chụp giá gần nhất; chưa xác minh độ trễ của nguồn.",
        clockNote: "Giờ được hiển thị đúng như nguồn cung cấp; nguồn chưa xác định múi giờ.",
        polling: "Kiểm tra giá mỗi 30 giây khi phần này đang mở và tab đang hiển thị.",
        historical: "Các phiên trước đã kết thúc",
        excludedToday: "Không đưa dữ liệu của ngày hiện tại vào biểu đồ lịch sử.",
        chart: "Giá đóng cửa theo phiên",
        rows: "Dữ liệu tại nguồn",
        more: "Xem thêm dòng",
        fewer: "Thu gọn",
        scroll: "Cuộn ngang để xem các cột còn lại.",
        quality:
          "Một số ô hoặc dòng không hợp lệ đã được bỏ qua. Kiểm tra nguồn trước khi sử dụng.",
        conflicts: "Nguồn có dữ liệu mâu thuẫn; không suy diễn giá trị còn thiếu.",
        readMore: "Đọc nội dung",
        publicTitle: "Tìm nguồn công khai",
        publicResultsTitle: "Kết quả tra cứu",
        publicIntro: "Tìm và đọc nguồn về mã đã chọn theo câu hỏi.",
        publicLabel: "Nội dung cần tìm",
        publicPlaceholder: "Ví dụ: Báo cáo tài chính gần nhất và công bố của doanh nghiệp",
        publicButton: "Tìm nguồn công khai",
        publicLoading: "Đang tìm và đọc nguồn…",
        publicDisabled:
          "Tìm nguồn bằng AI chưa sẵn sàng. Vẫn có thể tra cứu giá và thông tin công khai.",
        publicBoundary:
          "Kết quả đọc nguồn để tham khảo. Chưa tạo hồ sơ phân tích hoặc xác nhận số liệu báo cáo tài chính.",
        publicEmpty: "Chưa đọc được nguồn phù hợp cho yêu cầu này.",
        publicRead: "Đã đọc nội dung",
        publicPartial: "Đọc được một phần",
        publicIncomplete: "Kết quả đọc nguồn chưa đầy đủ.",
        publicUnavailable: "Chưa đọc được nội dung",
        limitations: "Giới hạn đọc nguồn",
        publicError: "Chưa hoàn tất việc tìm nguồn. Thử lại sau.",
        discoveryNotes: "Ghi chú lúc tìm liên kết, trước khi đọc nguồn",
        sourceMethod: "Cách đọc & phạm vi nguồn",
        stopWaiting: "Dừng chờ",
        pause: "Tạm dừng tự cập nhật",
        resume: "Tiếp tục tự cập nhật",
        autoUpdates: "Cập nhật mỗi 30 giây",
        paused: "Đã tạm dừng tự cập nhật",
        sourceDetails: "Chi tiết nguồn",
        priceDelay: "Chưa xác minh độ trễ",
        pauseShort: "Tạm dừng",
        resumeShort: "Tiếp tục",
      }
    : {
        title: "Market research",
        subtitle: "Prices, history and company information",
        intro: "Look up public data for the selected stock and exchange.",
        dataset: "Dataset",
        quote: "Last price",
        history: "Trading history",
        company: "Company information",
        refresh: "Refresh data",
        loading: "Reading the public source…",
        empty: "The source has no data for this selection.",
        choose: "Choose a stock to look up its data.",
        fetched: "Source retrieved",
        sourceDate: "Source data date",
        sourceClock: "Source time",
        missing: "Not provided",
        unknownUnit: "Not specified by the source",
        unknownDate: "The source did not provide an effective date",
        stale: "Using a previous snapshot; the data may have changed.",
        unsaved:
          "This snapshot could not be saved locally; a later lookup may need to fetch it again.",
        intraday: "Latest price snapshot; the source delay is unverified.",
        clockNote: "The time is shown exactly as supplied; the source timezone is unspecified.",
        polling: "Checks prices every 30 seconds while this panel is open and the tab is visible.",
        historical: "Completed prior sessions",
        excludedToday: "The current calendar day is excluded from the history chart.",
        chart: "Closing price by session",
        rows: "Source data",
        more: "Show more rows",
        fewer: "Show fewer",
        scroll: "Scroll horizontally to see the remaining columns.",
        quality: "Some invalid cells or rows were omitted. Check the source before using the data.",
        conflicts: "The source contains conflicting data; missing values are not inferred.",
        readMore: "Read content",
        publicTitle: "Find public sources",
        publicResultsTitle: "Research results",
        publicIntro: "Find and read sources about the selected stock using your question.",
        publicLabel: "What to find",
        publicPlaceholder: "For example: Latest financial statements and company disclosures",
        publicButton: "Find public sources",
        publicLoading: "Finding and reading sources…",
        publicDisabled:
          "AI source research is unavailable. Public prices and company information remain available.",
        publicBoundary:
          "Source excerpts are for reference. This does not create an analysis dossier or verify financial statement figures.",
        publicEmpty: "No relevant source could be read for this request.",
        publicRead: "Content read",
        publicPartial: "Partially read",
        publicIncomplete: "The source reading is incomplete.",
        publicUnavailable: "Content unavailable",
        limitations: "Reading limitations",
        publicError: "Source research could not be completed. Try again later.",
        discoveryNotes: "Discovery notes recorded before reading",
        sourceMethod: "Reading method & source coverage",
        stopWaiting: "Stop waiting",
        pause: "Pause automatic updates",
        resume: "Resume automatic updates",
        autoUpdates: "Updates every 30 seconds",
        paused: "Automatic updates paused",
        sourceDetails: "Source details",
        priceDelay: "Delay unverified",
        pauseShort: "Pause",
        resumeShort: "Resume",
      };

const fields = {
  date: ["Ngày", "Date"],
  time: ["Thời gian", "Time"],
  open: ["Mở cửa", "Open"],
  high: ["Cao nhất", "High"],
  low: ["Thấp nhất", "Low"],
  close: ["Đóng cửa", "Close"],
  volume: ["Khối lượng khớp lệnh", "Matched volume"],
  matchedValue: ["Giá trị khớp lệnh", "Matched value"],
  basicPrice: ["Giá tham chiếu", "Reference price"],
  ceilingPrice: ["Giá trần", "Ceiling price"],
  floorPrice: ["Giá sàn", "Floor price"],
  average: ["Giá bình quân", "Average price"],
  putThroughVolume: ["Khối lượng thỏa thuận", "Put-through volume"],
  putThroughValue: ["Giá trị thỏa thuận", "Put-through value"],
  change: ["Thay đổi", "Change"],
  pctChange: ["Thay đổi (%)", "Change (%)"],
  code: ["Mã chứng khoán", "Stock symbol"],
  floor: ["Sàn", "Exchange"],
  vnName: ["Tên tiếng Việt", "Vietnamese name"],
  enName: ["Tên tiếng Anh", "English name"],
  foundDate: ["Ngày thành lập", "Founded"],
  taxCode: ["Mã số thuế", "Tax number"],
  registrationCode: ["Mã đăng ký", "Registration number"],
  vnAddress: ["Địa chỉ tiếng Việt", "Vietnamese address"],
  enAddress: ["Địa chỉ tiếng Anh", "English address"],
  website: ["Trang doanh nghiệp", "Company website"],
  employees: ["Nhân viên", "Employees"],
  branches: ["Chi nhánh", "Branches"],
  vnSummary: ["Giới thiệu tiếng Việt", "Vietnamese overview"],
  enSummary: ["Giới thiệu tiếng Anh", "English overview"],
  companyId: ["Mã doanh nghiệp tại nguồn", "Source company identifier"],
};
export const fieldLabel = (key, locale, dataset) =>
  key === "close" && dataset === "quote"
    ? marketCopy(locale).quote
    : (fields[key]?.[locale === "vi" ? 0 : 1] ?? key);
